export default {
    actions: {
        async fetchProducts({commit}) {
            try {
                const res = await fetch('http://localhost:3000')
                const products = await res.json()

                commit('updateProducts', products)
            } catch(e) {
                console.log(e);
            }
            
        }
    },
    mutations: {
        updateProducts(state, products) {
            if (products) {
                state.products = products
            } 
        }
    },
    state: {
        products: [
            {id: 1, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 10000, discount: 'discount'},
            {id: 2, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 12000, discount: 'new'},
            {id: 3, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 8000, discount: 'discount'},
            {id: 4, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: true, image: 'plug.png', price: 10400, discount: 'discount'},
            {id: 5, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 25000, discount: 'discount'},
            {id: 6, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 7000, discount: 'new'},
            {id: 7, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 5000, discount: 'discount'},
            {id: 8, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 44000, discount: 'new'},
            {id: 9, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 12000, discount: 'discount'},
            {id: 11, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 1500, discount: 'new'},
            {id: 10, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 105000, discount: 'new'},
            {id: 12, name: 'Название товара на две строки', article: '085978891', fullName: 'Длинное название товара, расположенное на две строки', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere earum reprehenderit mollitia aliquam consectetur, nam quia tempore sit pariatur perspiciatis iure quisquam ullam perferendis! Cum voluptatem dignissimos, itaque natus dolorem voluptate dolor. Perferendis placeat cupiditate, architecto quaerat harum ea necessitatibus ullam reprehenderit reiciendis maxime unde odit tempore illo atque corrupti fugiat ut mollitia doloremque. Vero inventore ducimus similique vel animi obcaecati quod nobis quasi maiores, voluptate, quae quibusdam et voluptas corporis fuga illo earum optio, accusamus vitae aliquam officiis? Iure voluptatem ea laboriosam rerum voluptatibus, quidem atque distinctio vitae labore error sunt officia deserunt, officiis quos fugiat veniam ipsa a!', like: false, image: 'plug.png', price: 900, discount: 'discount'}
        ]
    },
    getters: {
        allProducts(state) {
            return state.products
        }
    }
}